all: codegen10 codegen11 codegenpostfix


codegen10: 
	g++ -O3 main.10digits.cpp -o codegen.10digits
codegen11:
	g++ -O3 main.11digits.cpp -o codegen.11digits
codegenpostfix:
	g++ -O3 main.postfix.cpp -o codegen.postfix

